### ISSUE TITLE
Settings seem to have no effect

### ISSUE THREAD

**Issue by un1versal** [notspiff/screensaver.matrixtrails#2] opened 2015-09-26 06:26 UTC
No matter what one chooses it makes no difference visually.

```
<settings>
  <setting id="columns"   label="30000" type="slider" option="int" range="1,1,200" default="1"/>
  <setting id="rows"      label="30001" type="slider" option="int" range="1,1,200" default="1"/>
  <setting id="chars"     label="30002" type="slider" option="int" range="1,1,100" default="1"/>
  <setting id="charsizex" label="30003" type="slider" option="float" range="0,0.01,1.0" default="0.70"/>
  <setting id="charsizey" label="30004" type="slider" option="float" range="0,0.01,1.0" default="0.60"/>
</settings>
```

looks exactly the same to me as default https://github.com/notspiff/screensaver.matrixtrails/blob/master/screensaver.matrixtrails/resources/settings.xml

**Comment by notspiff** [comment] 2015-09-26 06:31
thanks. https://github.com/notspiff/screensaver.matrixtrails/commit/cb9020e1f90e7dc78466590f7f16103f0a4c504ctry

**Comment by uNiversaI** [comment] 2015-09-26 06:47
mmm black screen now.

**Comment by uNiversaI** [comment] 2015-09-26 06:49
yep, black screen only

**Comment by akva2** [comment] 2015-09-26 06:56
fixed now.

**Comment by uNiversaI** [comment] 2015-09-26 07:06
Almost.

the character width and height seems to be ignored now and you need to make it 200 collumns and 200 rows to have a tiny character lese its a huge fat character

**Comment by un1versal** [comment] 2015-10-06 16:26
This last comment is still an issue

**Comment by akva2** [comment] 2015-10-06 16:30
and i don't know how to fix it.

**Comment by un1versal** [comment] 2015-10-06 16:43
bummer. Question is who does?

**Comment by akva2** [comment] 2015-10-06 16:48
yes, i know part of the problem is that my range for the setting is wrong. but even if i fix that, it just screws up but for different values of the setting.

whoever speaks dx8 AND opengl as the original code is the original xbox dx8 code. i don't really know either. i know the maths of 3d graphics so i can sorta grok it based on that. it's pure luck i got anything on screen really ;)

**Comment by un1versal** [comment] 2015-10-06 17:07
@afedchin might be able to help maybe

**Comment by afedchin** [comment] 2015-10-07 07:24
uh?

**Comment by un1versal** [comment] 2015-10-07 08:11
> uh?

You speak DX? any ideas?

**Comment by afedchin** [comment] 2015-10-07 08:37
I think this two lines https://github.com/notspiff/screensaver.matrixtrails/blob/master/src/column.cpp#L97 are wrong, uv shouldn't depend on config values and sould depend only on texture params see here https://github.com/notspiff/screensaver.matrixtrails/blob/master/src/main.cpp#L189

**Comment by notspiff** [comment] 2015-10-07 08:43
funny thing is that code is 100% unmodified from the xbox code. i think i
get it now.

there must have been a rouge option in the xbox xml that nobody ever
flipped. it was probably just there for easing texture changes. i blindly
converted all xml options to settings. so basically the cure is to kill the
setting.

**Comment by notspiff** [comment] 2015-10-07 10:04
okay, fixed now. also fixed the rows setting - it set columns (c&p error).

**Closed by notspiff** 2015-10-07 10:04 UTC

**Comment by un1versal** [comment] 2015-10-07 10:29
Well... Would you hate me more or less if I was to tell you there's something really wrong happening with the number of characters setting...

**Comment by notspiff** [comment] 2015-10-07 10:30
what's wrong with that? it is just a bit confusing. there's a fixed number of chars, the rest will be blank and then randomized. a higher value means more "air" between chars.

**Comment by un1versal** [comment] 2015-10-07 10:33
Try it, reduce the number of !"air" to 1, you will see what I mean. then increase to 5~10, then increase to 80 and above.

If its empty space then this setting is even odder

**Comment by un1versal** [comment] 2015-10-07 10:42
imo the only setting that works properly is Number of collumns, number of rows and number of characters dont behave nicely

**Comment by notspiff** [comment] 2015-10-07 11:08
setting removed.

**Comment by un1versal** [comment] 2015-10-07 11:23
And now you killed the screensaver.

I was right.

After testing that last removing characters and playing with the two remaining settings 

I did a ```rm -rf screensaver.matrixtrails ```

Useless now.
